# Resolver react_native_pods.rb con node para permitir la elevación
def node_require(script)
  # Resolver script con node para permitir la elevación
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

# Úsalo para requerir los scripts de react-native y de este paquete:
node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

# ⬇️ descomenta los permisos que necesitas
setup_permissions([
# 'AppTrackingTransparency',
# 'Bluetooth',
# 'Calendars',
# 'CalendarsWriteOnly',
'Camera',
# 'Contacts',
# 'FaceID',
# 'LocationAccuracy',
# 'LocationAlways',
# 'LocationWhenInUse',
# 'MediaLibrary',
# 'Microphone',
# 'Motion',
# 'Notifications',
# 'PhotoLibrary',
# 'PhotoLibraryAddOnly',
# 'Reminders',
# 'Siri',
# 'SpeechRecognition',
# 'StoreKit',
])

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
Pod::UI.puts "Configurando Pod con #{linkage}ally enlazado Frameworks".green
use_frameworks! :linkage => linkage.to_sym
end

target 'pruebaTecnicaGlobalThink' do
config = use_native_modules!

use_react_native!(
 :path => config[:reactNativePath],
 # Una ruta absoluta a la raíz de tu aplicación.
 :app_path => "#{Pod::Config.instance.installation_root}/.."
)

target 'pruebaTecnicaGlobalThinkTests' do
 inherit! :complete
 # Pods para pruebas
end

post_install do |installer|
 # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
 react_native_post_install(
   installer,
   config[:reactNativePath],
   :mac_catalyst_enabled => false,
   # :ccache_enabled => true
 )
end
end
